//============================================================================
//  Reed-Solomon codec test: golden vectors generated by the reference
//  implementation (Previous src/rs.c compiled standalone, see
//  tb/gen_rs_vectors.c) drive the real next_rs:
//
//  For each vector: encode the 1024 data bytes and compare all 1296
//  output bytes with the reference encoder; then load the corrupted
//  sector, decode, and compare the corrected 1024 bytes and the
//  corrected-error count.  Vector 1 uses the exact corruption pattern
//  of the boot ROM ECC system test (36 byte errors, the count the ROM
//  checks in ecc_cnt).
//============================================================================

`timescale 1ns/1ps

module tb_next_rs;

reg clk = 0;
always #5 clk = ~clk;

reg reset = 1;

reg  start_enc = 0, start_dec = 0;
wire done, fail;
wire [7:0] err_count;
wire [10:0] b_addr;
wire [7:0] b_wdata;
wire b_we;

reg [7:0] buffer [0:1295];
reg [7:0] b_q;
always @(posedge clk) begin
	if (b_we) buffer[b_addr] <= b_wdata;
	b_q <= buffer[b_addr];
end

next_rs dut
(
	.clk(clk), .reset(reset),
	.start_encode(start_enc), .start_decode(start_dec),
	.done(done), .fail(fail), .err_count(err_count),
	.b_addr(b_addr), .b_rdata(b_q), .b_wdata(b_wdata), .b_we(b_we)
);

// vectors: per set: 1024 data, 1296 encoded, 1296 corrupted, 1024 decoded
reg [7:0] vec [0:9279];

integer errors = 0;

task check;
	input cond;
	input [255:0] name;
	begin
		if (cond) $display("PASS: %0s", name);
		else begin $display("FAIL: %0s", name); errors = errors + 1; end
	end
endtask

task wait_done;
	integer n;
	begin
		n = 0;
		while (!done && n < 2000000) begin
			@(posedge clk);
			n = n + 1;
		end
		if (!done) begin
			$display("FAIL: codec timed out");
			errors = errors + 1;
			$finish;
		end
		@(posedge clk);
	end
endtask

integer i, base, bad;
reg [7:0] exp_cnt;

task run_set;
	input integer setbase;
	input [7:0] expcnt;
	input [127:0] label;
	begin
		// encode
		for (i = 0; i < 1296; i = i + 1)
			buffer[i] = (i < 1024) ? vec[setbase + i] : 8'h00;
		@(posedge clk);
		start_enc <= 1;
		@(posedge clk);
		start_enc <= 0;
		wait_done;
		bad = 0;
		for (i = 0; i < 1296; i = i + 1)
			if (buffer[i] != vec[setbase + 1024 + i]) bad = bad + 1;
		$display("%0s: encode mismatches: %0d", label, bad);
		check(bad == 0, "encode matches the reference");

		// decode the corrupted sector
		for (i = 0; i < 1296; i = i + 1)
			buffer[i] = vec[setbase + 2320 + i];
		@(posedge clk);
		start_dec <= 1;
		@(posedge clk);
		start_dec <= 0;
		wait_done;
		bad = 0;
		for (i = 0; i < 1024; i = i + 1)
			if (buffer[i] != vec[setbase + 3616 + i]) bad = bad + 1;
		$display("%0s: decode mismatches: %0d err_count=%0d (expect %0d) fail=%b",
		         label, bad, err_count, expcnt, fail);
		check(bad == 0, "decode corrects to the reference data");
		check(err_count == expcnt, "corrected error count matches");
		check(!fail, "no uncorrectable flag");
	end
endtask

initial begin
	$readmemh("rs_vectors.hex", vec);
	repeat (10) @(posedge clk);
	reset = 0;
	repeat (5) @(posedge clk);

	run_set(0, 8'd36, "vector1 (POST pattern)");
	run_set(4640, 8'd18, "vector2 (random)");

	if (errors == 0) $display("ALL PASS");
	else             $display("%0d FAILURES", errors);
	$finish;
end

endmodule
